# Generated by Django 3.0.5 on 2020-05-27 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Callout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('facility', models.CharField(choices=[('BWD', 'BWD'), ('CCH', 'CCH'), ('HND', 'HND'), ('SYO', 'SYO')], default='BWD', max_length=20)),
                ('callout_date', models.DateField(default=django.utils.timezone.now)),
                ('notification_time', models.TimeField(default=django.utils.timezone.now)),
                ('arrival_time', models.TimeField(default=django.utils.timezone.now)),
                ('completion_time', models.TimeField(default=django.utils.timezone.now)),
                ('mileage', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('ref_number', models.PositiveIntegerField(default=0)),
                ('findings', models.TextField(max_length=500)),
                ('actions_taken', models.TextField(max_length=500)),
                ('resolved_status', models.BooleanField()),
                ('follow_up_status', models.BooleanField()),
                ('support_required_status', models.BooleanField()),
                ('priority_status', models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3')], default='C1', max_length=5)),
                ('fault_case', models.CharField(choices=[('electrical', 'electrical'), ('leak', 'leak'), ('alarm', 'alarm'), ('medical_gas', 'medical_gas'), ('drainage_block', 'drainage_block'), ('temp_issues', 'temp_issues'), ('wear_tear', 'wear_tear')], default='C1', max_length=20)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(default=0)),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Callout',
                'verbose_name_plural': 'Callouts',
                'ordering': ('callout_date',),
            },
        ),
    ]
