# Generated by Django 3.0.5 on 2020-05-27 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('surname', models.CharField(default='', max_length=20)),
                ('position', models.CharField(default='', max_length=20)),
                ('photo', models.ImageField(default='default.jpg', upload_to='upload_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Info',
                'verbose_name_plural': 'Profiles',
                'ordering': ('first_name', 'surname'),
            },
        ),
    ]
